name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pipenv'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --deploy --dev --system

    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Run Tests
      run: pytest
